CREATE TABLE IF NOT EXISTS items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  content TEXT NOT NULL,
  category TEXT NOT NULL,
  priority TEXT NOT DEFAULT 'Medium',
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);


