services:
  flask:
    image: think_tank
    command: gunicorn -b 0.0.0.0:6000 app:app
    ports:
      - "6000:6000"
    volumes:
      - /home/ardi/think_tank/notes.db:/app/notes.db
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USE_TLS=${MAIL_USE_TLS}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
    restart: always

  streamlit:
    image: think_tank
    command: streamlit run stl.py --server.port 8502 --server.address 0.0.0.0
    ports:
      - "8502:8502"
    volumes:
      - /home/ardi/think_tank/notes.db:/app/notes.db
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USE_TLS=${MAIL_USE_TLS}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
    restart: always
    depends_on:
      - flask
