services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: think_tank_api
    command: gunicorn -b 0.0.0.0:6000 -w 1 --threads 4 --preload app:app
    ports:
      - "6000:6000"
    volumes:
      - /home/ardi/Projects/think_tank/notes.db:/app/notes.db
      - /home/ardi/Projects/think_tank/uploads:/app/uploads
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: always

  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: think_tank_frontend
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - API_URL=http://flask:6000
      - THINK_TANK_PASSWORD=${THINK_TANK_PASSWORD}
      - COOKIE_SECRET=${COOKIE_SECRET}
    depends_on:
      - flask
    restart: always
