FROM python:3.13-slim
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p /app/uploads

CMD ["gunicorn", "-b", "0.0.0.0:6000", "-w", "1", "--threads", "4", "--preload", "app:app"]
